Repository josemarluedke/frontile, pull requests merged in 2020-10, with the labels that each got.

#96 Delay calling validate on changeset form input to avoid errors
  packages/changeset-form/addon/components/changeset-form/fields/base.ts
Labels: Type: Bug

#97 Add selected class when checked
  packages/forms/addon/components/form-checkbox.hbs
  packages/forms/addon/components/form-radio.hbs
  packages/forms/tests/integration/components/form-checkbox-test.ts
  packages/forms/tests/integration/components/form-radio-test.ts
Labels: Type: Enhancement

#98 Revert "Add selected class when checked"
  packages/forms/addon/components/form-checkbox.hbs
  packages/forms/addon/components/form-radio.hbs
  packages/forms/tests/integration/components/form-checkbox-test.ts
  packages/forms/tests/integration/components/form-radio-test.ts
Labels: Type: Bug

#99 Fix failing test for ember-default
  packages/changeset-form/tests/integration/components/changeset-form/fields/textarea-test.ts
Labels: Type: Internal

#100 Upgrade Project Dependencies & Ember to v3.22
  package.json
  packages/buttons/package.json
  packages/changeset-form/package.json
  packages/changeset-form/tsconfig.json
  packages/core/package.json
  packages/docs/package.json
  packages/forms/package.json
  packages/notifications/package.json
  packages/notifications/tests/integration/components/notification-card-test.ts
  packages/overlays/package.json
  tsconfig.base.json
  yarn.lock
Labels: Type: Dependencies

#101 Add Drawer component
  packages/docs/app/components/demo/overlays/demo-drawer.hbs
  packages/docs/app/components/demo/overlays/demo-drawer.ts
  packages/docs/app/templates/docs/overlays/usage.md
  packages/forms/tailwind.js
  packages/notifications/tailwind.js
  packages/overlays/addon/components/drawer/body.hbs
  packages/overlays/addon/components/drawer/body.ts
  packages/overlays/addon/components/drawer/footer.hbs
  packages/overlays/addon/components/drawer/footer.ts
  packages/overlays/addon/components/drawer/header.hbs
  packages/overlays/addon/components/drawer/header.ts
  packages/overlays/addon/components/drawer/index.hbs
  packages/overlays/addon/components/drawer/index.ts
  packages/overlays/addon/components/overlay.hbs
  packages/overlays/addon/tailwind/default-options.js
  packages/overlays/app/components/drawer.js
  packages/overlays/app/components/drawer/body.js
  packages/overlays/app/components/drawer/footer.js
  packages/overlays/app/components/drawer/header.js
  packages/overlays/package.json
  packages/overlays/tailwind.js
  packages/overlays/tests/dummy/app/components/demo-drawer.hbs
  packages/overlays/tests/dummy/app/components/demo-drawer.ts
  packages/overlays/tests/dummy/app/components/demo-modal.hbs
  packages/overlays/tests/dummy/app/styles/tailwind.config.js
  packages/overlays/tests/dummy/app/templates/index.hbs
  packages/overlays/tests/integration/components/drawer-test.ts
  packages/overlays/tests/integration/components/drawer/body-test.ts
  packages/overlays/tests/integration/components/drawer/footer-test.ts
  packages/overlays/tests/integration/components/drawer/header-test.ts
  packages/tailwindcss-plugin-helpers/src/index.js
  yarn.lock
Labels: Type: Enhancement

#102 Upgrade Ember CLI to v3.22 & Tailwind to latest
  packages/buttons/package.json
  packages/changeset-form/package.json
  packages/core/package.json
  packages/docs/package.json
  packages/forms/package.json
  packages/notifications/package.json
  packages/overlays/package.json
  yarn.lock
Labels: Type: Dependencies

#103 Move tailwind/default-options to a new location
  .eslintrc.js
  packages/buttons/tailwind/default-options.js
  packages/buttons/tailwind/index.js
  packages/buttons/tests/dummy/app/styles/tailwind.config.js
  packages/forms/tailwind/default-options.js
  packages/forms/tailwind/index.js
  packages/forms/tests/dummy/app/styles/tailwind.config.js
  packages/notifications/tailwind/default-options.js
  packages/notifications/tailwind/index.js
  packages/notifications/tests/dummy/app/styles/tailwind.config.js
  packages/notifications/tsconfig.json
  packages/overlays/ember-cli-build.js
  packages/overlays/tailwind/default-options.js
  packages/overlays/tailwind/index.js
  packages/overlays/tests/dummy/app/styles/tailwind.config.js
Labels: Type: Bug

#104 Add Size option to Modal component
  packages/docs/app/components/demo/overlays/demo-modal.hbs
  packages/docs/app/components/demo/overlays/demo-modal.ts
  packages/overlays/addon/components/modal/index.hbs
  packages/overlays/addon/components/modal/index.ts
  packages/overlays/tailwind/default-options.js
  packages/overlays/tailwind/index.js
  packages/overlays/tests/dummy/app/components/demo-modal.hbs
  packages/overlays/tests/dummy/app/components/demo-modal.ts
  packages/overlays/tests/integration/components/drawer-test.ts
  packages/overlays/tests/integration/components/modal-test.ts
Labels: Type: Breaking Change, Type: Enhancement

#105 Fix modal border color config
  packages/overlays/tailwind/default-options.js
Labels: Type: Bug

#106 [core] Create CloseButton component
  packages/core/addon/components/close-button.hbs
  packages/core/addon/components/close-button.ts
  packages/core/app/components/close-button.js
  packages/core/ember-cli-build.js
  packages/core/package.json
  packages/core/tailwind/default-options.js
  packages/core/tailwind/index.js
  packages/core/tests/dummy/app/styles/app.css
  packages/core/tests/dummy/app/templates/application.hbs
  packages/core/tests/dummy/config/tailwind.config.js
  packages/core/tests/integration/components/close-button-test.ts
Labels: Type: Enhancement

#107 Migrate Modal & Drawer to use CloseButton component from core
  packages/core/addon/components/close-button.hbs
  packages/core/addon/components/close-button.ts
  packages/core/tests/integration/components/close-button-test.ts
  packages/overlays/addon/components/drawer/index.hbs
  packages/overlays/addon/components/drawer/index.ts
  packages/overlays/addon/components/modal/index.hbs
  packages/overlays/addon/components/modal/index.ts
  packages/overlays/tailwind/default-options.js
  packages/overlays/tailwind/index.js
  packages/overlays/tests/dummy/app/components/demo-drawer.hbs
  packages/overlays/tests/dummy/app/styles/tailwind.config.js
  packages/overlays/tests/integration/components/drawer-test.ts
  packages/overlays/tests/integration/components/modal-test.ts
  packages/overlays/tsconfig.json
Labels: Type: Breaking Change

#108 Add Core docs for Installation & CloseButton
  packages/core/tailwind/default-options.js
  packages/docs/app/router.js
  packages/docs/app/styles/tailwind.config.js
  packages/docs/app/templates/docs.hbs
  packages/docs/app/templates/docs/core/close-button.md
  packages/docs/app/templates/docs/core/index.md
  packages/docs/app/templates/docs/overlays/index.md
Labels: Type: Documentation

#109 Refactor TailwindCSS plugins structure to a common interface
  packages/buttons/addon/components/button.hbs
  packages/buttons/ember-cli-build.js
  packages/buttons/tailwind/default-options.js
  packages/buttons/tailwind/index.js
  packages/buttons/tests/dummy/app/config/tailwind.config.js
  packages/core/tailwind/index.js
  packages/core/tests/dummy/config/tailwind.config.js
  packages/docs/app/templates/docs/buttons/index.md
  packages/docs/app/templates/docs/core/index.md
  packages/docs/app/templates/docs/notifications/index.md
  packages/docs/app/templates/docs/overlays/index.md
  packages/notifications/addon/components/notification-card.hbs
  packages/notifications/addon/components/notification-card.ts
  packages/notifications/addon/components/notifications-container.hbs
  packages/notifications/package.json
  packages/notifications/tailwind/default-options.js
  packages/notifications/tailwind/index.js
  packages/notifications/tests/dummy/app/styles/tailwind.config.js
  packages/notifications/tests/integration/components/notification-card-test.ts
  packages/overlays/addon/components/drawer/index.hbs
  packages/overlays/addon/components/drawer/index.ts
  packages/overlays/addon/components/modal/index.hbs
  packages/overlays/addon/components/modal/index.ts
  packages/overlays/addon/components/overlay.hbs
  packages/overlays/addon/components/overlay.ts
  packages/overlays/tailwind/default-options.js
  packages/overlays/tailwind/index.js
  packages/overlays/tests/integration/components/overlay-test.ts
  packages/tailwindcss-plugin-helpers/src/index.js
Labels: Type: Breaking Change

#110 Create helper to add CSS classes
  packages/core/addon/components/close-button.hbs
  packages/core/addon/components/close-button.ts
  packages/core/addon/helpers/use-frontile-class.ts
  packages/core/app/helpers/use-frontile-class.js
  packages/core/tests/integration/helpers/use-frontile-class-test.ts
  packages/notifications/addon/components/notification-card.hbs
  packages/notifications/addon/components/notifications-container.hbs
  packages/overlays/addon/components/drawer/body.hbs
  packages/overlays/addon/components/drawer/footer.hbs
  packages/overlays/addon/components/drawer/header.hbs
  packages/overlays/addon/components/drawer/index.hbs
  packages/overlays/addon/components/modal/body.hbs
  packages/overlays/addon/components/modal/footer.hbs
  packages/overlays/addon/components/modal/header.hbs
  packages/overlays/addon/components/modal/index.hbs
  packages/overlays/addon/components/modal/index.ts
  packages/overlays/addon/components/overlay.hbs
Labels: Type: Enhancement

#111 Remove usage of deprecated getWithDefault
  packages/notifications/addon/-private/get-config.ts
Labels: Type: Enhancement

#114 Add focusTrapOptions to overlays
  packages/overlays/addon/components/overlay.hbs
  packages/overlays/addon/components/overlay.ts
Labels: Type: Enhancement
