Repository josemarluedke/frontile, pull requests merged in 2020-06, with the labels that each got.

#74 docs: add missing changeset import
  packages/docs/app/templates/docs/changeset-form/usage.md
Labels: Type: Documentation

#79 Run GitHub Actions on Pull-Request
  .github/workflows/ci.yml
Labels: Type: Internal

#77 fix(changeset-form): more generous versioning for changeset
  packages/changeset-form/package.json
Labels: Type: Dependencies

#80 Refresh yarn.lock due to changeset version change
  yarn.lock
Labels: Type: Dependencies
