Repository josemarluedke/frontile, pull requests merged in 2021-04, with the labels that each got.

#154 Upgrade Project Dependencies / Ember v3.26
  package.json
  packages/buttons/package.json
  packages/changeset-form/addon/components/changeset-form/fields/checkbox.hbs
  packages/changeset-form/addon/components/changeset-form/fields/radio.hbs
  packages/changeset-form/package.json
  packages/core/addon/components/close-button.hbs
  packages/core/package.json
  packages/forms/addon/components/form-checkbox.hbs
  packages/forms/addon/components/form-radio.hbs
  packages/forms/package.json
  packages/forms/tests/dummy/app/components/form-example.hbs
  packages/notifications/package.json
  packages/overlays/addon/components/overlay.hbs
  packages/overlays/package.json
  packages/tailwindcss-plugin-helpers/package.json
  site/lib/docfy-theme/addon/components/page-headings.hbs
  site/lib/docfy-theme/package.json
  site/package.json
  yarn.lock
Labels: Type: Dependencies

#152 fix(overlays): set modal/drawer body to overflow auto
  packages/overlays/tailwind/default-options.js
Labels: Type: Bug

#156 Simplify CI
  .github/workflows/ci.yml
Labels: Type: Internal

#158 Run prettier in mardown files
  packages/buttons/README.md
  packages/buttons/addon/components/button.md
  packages/changeset-form/README.md
  packages/changeset-form/docs/changeset-form-usage-demo/demo.md
  packages/changeset-form/docs/changeset-form-usage.md
  packages/core/README.md
  packages/core/addon/components/collapsible.md
  packages/core/docs/focus-management.md
  packages/forms/README.md
  packages/forms/addon/components/form-input-demo/hint.md
  packages/forms/addon/components/form-input-demo/no-label.md
  packages/forms/addon/components/form-input-demo/simple.md
  packages/forms/addon/components/form-input-demo/with-button.md
  packages/notifications/README.md
  packages/notifications/addon/components/notifications-container.md
  packages/notifications/docs/notifications-usage-demo/demo.md
  packages/overlays/README.md
  packages/overlays/addon/components/drawer/demo/composition.md
  packages/overlays/addon/components/drawer/demo/placements.md
  packages/overlays/addon/components/drawer/demo/sizes.md
  packages/overlays/addon/components/drawer/demo/usage.md
  packages/overlays/addon/components/drawer/index.md
  packages/overlays/addon/components/modal/demo/sizes.md
  packages/overlays/addon/components/modal/demo/usage.md
  packages/overlays/addon/components/overlay-demo/usage.md
  packages/tailwindcss-plugin-helpers/README.md
Labels: Type: Internal

#159 Upgrade dependencies - use latest ember-focus-trap
  package.json
  packages/buttons/package.json
  packages/changeset-form/package.json
  packages/core/package.json
  packages/forms/package.json
  packages/notifications/package.json
  packages/overlays/package.json
  site/lib/docfy-theme/package.json
  site/package.json
  yarn.lock
Labels: Type: Dependencies
