Repository josemarluedke/frontile, pull requests merged in 2022-03, with the labels that each got.

#201 Consolidate templates into test-app
  test-app/app/components/buttons/demo.hbs
  test-app/app/components/changeset-form/countries.ts
  test-app/app/components/changeset-form/demo.hbs
  test-app/app/components/changeset-form/demo.ts
  test-app/app/components/core/collapsible-demo.hbs
  test-app/app/components/core/collapsible-demo.ts
  test-app/app/components/core/demo.hbs
  test-app/app/components/forms/form-example.hbs
  test-app/app/components/forms/form-example.ts
  test-app/app/components/forms/navigation.hbs
  test-app/app/components/forms/style-variants.hbs
  test-app/app/components/forms/style-variants.ts
  test-app/app/components/navigation.hbs
  test-app/app/components/notifications/demo.hbs
  test-app/app/components/notifications/demo.ts
  test-app/app/components/overlays/demo-drawer.hbs
  test-app/app/components/overlays/demo-drawer.ts
  test-app/app/components/overlays/demo-modal.hbs
  test-app/app/components/overlays/demo-modal.ts
  test-app/app/config/tailwind.config.js
  test-app/app/router.js
  test-app/app/routes/buttons.ts
  test-app/app/routes/changeset-form.ts
  test-app/app/routes/core.ts
  test-app/app/routes/forms.ts
  test-app/app/routes/forms/style-variants.ts
  test-app/app/routes/notifications.ts
  test-app/app/routes/overlays.ts
  test-app/app/templates/application.hbs
  test-app/app/templates/buttons.hbs
  test-app/app/templates/changeset-form.hbs
  test-app/app/templates/core.hbs
  test-app/app/templates/forms/index.hbs
  test-app/app/templates/forms/style-variants.hbs
  test-app/app/templates/notifications.hbs
  test-app/app/templates/overlays.hbs
  test-app/tests/unit/routes/buttons-test.ts
  test-app/tests/unit/routes/changeset-form-test.ts
  test-app/tests/unit/routes/core-test.ts
  test-app/tests/unit/routes/forms-test.ts
  test-app/tests/unit/routes/forms/style-variants-test.ts
  test-app/tests/unit/routes/notifications-test.ts
  test-app/tests/unit/routes/overlays.ts
  yarn.lock
Labels: Type: Internal

#202 Remove old demo templates and components from each addon dummy app
  packages/buttons/ember-cli-build.js
  packages/buttons/package.json
  packages/buttons/tests/dummy/app/config/tailwind.config.js
  packages/buttons/tests/dummy/app/styles/app.css
  packages/buttons/tests/dummy/app/templates/application.hbs
  packages/buttons/tests/dummy/app/templates/index.hbs
  packages/changeset-form/ember-cli-build.js
  packages/changeset-form/package.json
  packages/changeset-form/tests/dummy/app/components/changeset-form-example.hbs
  packages/changeset-form/tests/dummy/app/components/changeset-form-example.ts
  packages/changeset-form/tests/dummy/app/components/countries.ts
  packages/changeset-form/tests/dummy/app/styles/app.css
  packages/changeset-form/tests/dummy/app/styles/tailwind.config.js
  packages/changeset-form/tests/dummy/app/templates/application.hbs
  packages/changeset-form/tests/dummy/app/templates/index.hbs
  packages/core/ember-cli-build.js
  packages/core/package.json
  packages/core/tests/dummy/app/components/collapsible-demo.hbs
  packages/core/tests/dummy/app/components/collapsible-demo.ts
  packages/core/tests/dummy/app/styles/app.css
  packages/core/tests/dummy/app/templates/application.hbs
  packages/core/tests/dummy/config/tailwind.config.js
  packages/forms/ember-cli-build.js
  packages/forms/package.json
  packages/forms/tests/dummy/app/components/.gitkeep
  packages/forms/tests/dummy/app/components/form-example.hbs
  packages/forms/tests/dummy/app/components/form-example.ts
  packages/forms/tests/dummy/app/components/style-variants.hbs
  packages/forms/tests/dummy/app/components/style-variants.ts
  packages/forms/tests/dummy/app/router.js
  packages/forms/tests/dummy/app/routes/.gitkeep
  packages/forms/tests/dummy/app/routes/index.ts
  packages/forms/tests/dummy/app/routes/style-variants.ts
  packages/forms/tests/dummy/app/styles/app.css
  packages/forms/tests/dummy/app/styles/tailwind.config.js
  packages/forms/tests/dummy/app/templates/.gitkeep
  packages/forms/tests/dummy/app/templates/application.hbs
  packages/forms/tests/dummy/app/templates/index.hbs
  packages/forms/tests/dummy/app/templates/style-variants.hbs
  packages/notifications/ember-cli-build.js
  packages/notifications/package.json
  packages/notifications/tests/dummy/app/components/demo.hbs
  packages/notifications/tests/dummy/app/components/demo.ts
  packages/notifications/tests/dummy/app/styles/app.css
  packages/notifications/tests/dummy/app/styles/tailwind.config.js
  packages/notifications/tests/dummy/app/templates/application.hbs
  packages/notifications/tests/dummy/app/templates/index.hbs
  packages/overlays/ember-cli-build.js
  packages/overlays/package.json
  packages/overlays/tests/dummy/app/components/demo-drawer.hbs
  packages/overlays/tests/dummy/app/components/demo-drawer.ts
  packages/overlays/tests/dummy/app/components/demo-modal.hbs
  packages/overlays/tests/dummy/app/components/demo-modal.ts
  packages/overlays/tests/dummy/app/styles/app.css
  packages/overlays/tests/dummy/app/styles/tailwind.config.js
  packages/overlays/tests/dummy/app/templates/.gitkeep
  packages/overlays/tests/dummy/app/templates/application.hbs
  packages/overlays/tests/dummy/app/templates/index.hbs
Labels: Type: Internal

#203 Upgrade ember changeset dependencies to v4
  packages/changeset-form/package.json
  packages/changeset-form/types/ember-get-config.d.ts
  site/package.json
  test-app/package.json
  test-app/yarn.lock
  yarn.lock
Labels: Type: Dependencies

#204 Upgraded packages to use tailwindcss 3
  docs/installation.md
  packages/buttons/package.json
  packages/changeset-form/package.json
  packages/core/addon/components/visually-hidden.hbs
  packages/core/addon/components/visually-hidden.md
  packages/core/addon/styles/core.css
  packages/core/package.json
  packages/core/tailwind/index.js
  packages/forms/package.json
  packages/forms/types/ember-get-config.d.ts
  packages/notifications/package.json
  packages/overlays/package.json
  site/app/config/tailwind.config.js
  site/app/styles/app.css
  site/ember-cli-build.js
  site/package.json
  test-app/app/config/tailwind.config.js
  test-app/ember-cli-build.js
  test-app/package.json
  test-app/tests/integration/components/core/visually-hidden-test.ts
  yarn.lock
Labels: Type: Breaking Change

#205 Enable embroider safe for tests; Upgrade dependencies
  .github/workflows/ci.yml
  packages/buttons/package.json
  packages/changeset-form/package.json
  packages/core/package.json
  packages/forms/package.json
  packages/notifications/package.json
  packages/overlays/package.json
  test-app/package.json
  yarn.lock
Labels: Type: Enhancement

#207 404 page not found
  site/app/router.js
  site/app/templates/not-found.hbs
Labels: Type: Documentation

#206 Enable embroider optimized and Drop ChangesetForm::Context
  .github/workflows/ci.yml
  packages/changeset-form/addon/components/changeset-form/context/index.hbs
  packages/changeset-form/addon/components/changeset-form/index.hbs
  packages/changeset-form/app/components/changeset-form/context/index.js
  packages/changeset-form/docs/changeset-form-usage-demo/demo.md
  test-app/app/components/changeset-form/demo.hbs
  test-app/app/components/navigation.hbs
  test-app/tests/integration/components/changeset-form/changeset-form-test.ts
Labels: Type: Breaking Change

#209 Enable ember-canary tests
  .github/workflows/ci.yml
Labels: Type: Internal

#210 Add embroider deps to site
  site/ember-cli-build.js
  site/package.json
  yarn.lock
Labels: Type: Internal
