Repository josemarluedke/frontile, pull requests merged in 2024-01, with the labels that each got.

#250 Theming: Ability to add themes, add default light and dark modes
  packages/tailwindcss-plugin-helpers/LICENSE.md
  packages/tailwindcss-plugin-helpers/README.md
  packages/tailwindcss-plugin-helpers/package.json
  packages/tailwindcss-plugin-helpers/src/index.js
  packages/theme/.eslintignore
  packages/theme/package.json
  packages/theme/src/colors/semantic.ts
  packages/theme/src/colors/types.ts
  packages/theme/src/colors/util.ts
  packages/theme/src/components/button.ts
  packages/theme/src/components/close-button.ts
  packages/theme/src/components/forms/form-field.ts
  packages/theme/src/components/notification-card.ts
  packages/theme/src/components/overlays.ts
  packages/theme/src/plugin.ts
  packages/theme/src/plugin/default-config.ts
  packages/theme/src/plugin/overlays.ts
  packages/theme/src/plugin/power-select.ts
  packages/theme/src/plugin/resolve.ts
  packages/theme/src/plugin/transitions.ts
  packages/theme/src/services/theme-manager.ts
  packages/theme/src/types.ts
  packages/theme/unpublished-development-types/tailwindcss-ember-power-select.d.ts
  pnpm-lock.yaml
  test-app/app/components/changeset-form/demo.hbs
  test-app/app/components/core/collapsible-demo.hbs
  test-app/app/components/core/demo.hbs
  test-app/app/components/forms/form-example.hbs
  test-app/app/components/forms/navigation.hbs
  test-app/app/components/forms/style-variants.hbs
  test-app/app/components/navigation.hbs
  test-app/app/components/notifications/demo.hbs
  test-app/app/config/tailwind.config.js
  test-app/app/index.html
  test-app/app/templates/application.hbs
Labels: Type: Breaking Change

#252 Theme colors
  packages/theme/rollup.config.mjs
  packages/theme/src/colors.ts
  packages/theme/src/colors/defaults.ts
  packages/theme/src/colors/semantic.ts
  packages/theme/src/colors/types.ts
  packages/theme/src/plugin.ts
  test-app/app/components/.gitkeep
  test-app/app/components/navigation.hbs
  test-app/app/components/overlays/demo-drawer.hbs
  test-app/app/components/overlays/demo-modal.hbs
  test-app/app/components/theme-switcher.hbs
  test-app/app/components/theme-switcher.ts
  test-app/app/config/tailwind.config.js
  test-app/app/routes/index.ts
  test-app/app/templates/application.hbs
  test-app/app/templates/index.hbs
Labels: Type: Enhancement

#253 Feat: Add Chip component to buttons pkg
  .eslintrc.js
  packages/buttons/package.json
  packages/buttons/src/components/chip-demo/close-button.md
  packages/buttons/src/components/chip.gts
  packages/buttons/src/components/chip.md
  packages/buttons/src/template-registry.ts
  packages/theme/src/components/chip.ts
  packages/theme/src/components/index.ts
  pnpm-lock.yaml
  test-app/app/components/buttons/button.hbs
  test-app/app/components/buttons/chip.hbs
  test-app/app/templates/buttons.hbs
  test-app/ember-cli-build.js
  test-app/tailwind.config.js
  test-app/tests/integration/components/buttons/chip-test.ts
Labels: Type: Enhancement

#254 [site] Update site colors
  packages/theme/src/components/forms/form-field.ts
  site/app/config/tailwind.config.js
  site/app/index.html
  site/app/styles/docfy-demo.css
Labels: Type: Internal

#255 feat: Add ToggleButton component to buttons pkg
  packages/buttons/package.json
  packages/buttons/src/components/toggle-button.gts
  packages/buttons/src/template-registry.ts
  packages/theme/src/components/button.ts
  test-app/app/components/buttons/toggle-button.hbs
  test-app/app/components/buttons/toggle-button.ts
  test-app/app/templates/buttons.hbs
  test-app/tests/integration/components/buttons/buttons-test.ts
  test-app/tests/integration/components/buttons/toggle-button-test.ts
Labels: Type: Enhancement

#256 feat: Add ButtonGroup component to buttons pkg
  packages/buttons/package.json
  packages/buttons/rollup.config.mjs
  packages/buttons/src/components/button-group.gts
  packages/buttons/src/components/button-group.md
  packages/buttons/src/components/button.gts
  packages/buttons/src/components/button.md
  packages/buttons/src/components/chip-demo/close-button.md
  packages/buttons/src/components/chip.md
  packages/buttons/src/components/toggle-button.gts
  packages/buttons/src/components/toggle-button.md
  packages/buttons/src/index.ts
  packages/buttons/src/template-registry.ts
  packages/theme/src/components/button.ts
  pnpm-lock.yaml
  site/.docfy-config.js
  site/app/components/.gitkeep
  site/app/components/logo.gts
  site/app/components/logo.hbs
  site/app/routes/index.ts
  site/ember-cli-build.js
  site/package.json
  test-app/app/components/buttons/button-group.gts
  test-app/app/components/buttons/button.gts
  test-app/app/components/buttons/button.hbs
  test-app/app/components/buttons/chip.gts
  test-app/app/components/buttons/chip.hbs
  test-app/app/components/buttons/toggle-button.gts
  test-app/app/components/buttons/toggle-button.hbs
  test-app/app/components/buttons/toggle-button.ts
  test-app/app/templates/buttons.hbs
  test-app/ember-cli-build.js
  test-app/package.json
  test-app/tests/integration/components/buttons/button-group-test.ts
  test-app/tests/integration/components/buttons/buttons-test.ts
  test-app/tests/integration/components/buttons/toggle-button-test.ts
Labels: Type: Enhancement

#257 chore: update dependencies to latest
  package.json
  packages/buttons/package.json
  packages/changeset-form/package.json
  packages/core/package.json
  packages/forms/package.json
  packages/notifications/package.json
  packages/overlays/package.json
  packages/theme/package.json
  pnpm-lock.yaml
  site/package.json
  test-app/package.json
Labels: Type: Dependencies

#258 Progress bar component
  packages/buttons/package.json
  packages/buttons/src/components/progress-bar.gts
  packages/buttons/src/components/progress-bar.md
  packages/buttons/src/index.ts
  packages/buttons/src/template-registry.ts
  packages/theme/src/components/index.ts
  packages/theme/src/components/progress-bar.ts
  packages/theme/src/plugin.ts
  test-app/app/components/buttons/progress-bar.gts
  test-app/app/templates/buttons.hbs
  test-app/ember-cli-build.js
  test-app/tailwind.config.js
  test-app/tests/integration/components/buttons/progress-bar-test.ts
Labels: Type: Enhancement
